language: java
jdk:
  - openjdk8
script: ./mvnw clean install
script: [![Build Status](https://travis-ci.com/Navyasree-068/travis_ci.svg?branch=master)](https://travis-ci.com/Navyasree-068/travis_ci)

jobs:
   include:
     - stage: Test
        script: ./mvnw clean test
notifications:
  email: navyasree068@gmail.com

