language: java
jdk:
  - openjdk8
script: ./mvnw clean install
script: [![Build Status](https://travis-ci.com/username/projectname.svg?branch=master)](https://travis-ci.com/username/projectname)

jobs:
   include:
     - stage: Test
        script: ./mvnw clean test
notifications:
  email: navyasree068@gmail.com

